### ISSUE TITLE
Primeiros passos na seção de desenvolvimento

### ISSUE THREAD

**Issue by JoaoRMaia** [daniellopes04/cred-carbon-game#4]

**Comment by Thiolivs** [comment]
Motivo de estarmos fazendo, objetivos educacionais, historia do jogo (linhas gerais), documentar o processo, desde o inicio, detalhar a ideia por trás do jogo, problemas que solucionam, objetivos, ENDO, Mecânicas e o que cada dinâamica atinge de objetivo de aprendizado, Machinations

Conclusão: atingimos objetivos?
